const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),crypto=require('node:crypto');
process.chdir(require('node:path').resolve(__dirname,'..'));
function fixture(){
    let state={access:{admin:{role:'admin',active:true},waiter:{role:'waiter',active:true},kitchen:{role:'kitchen',active:true},cashier:{role:'cashier',active:true}},menu:{coffee:{name:'قهوة',price:25}},orders:{},tables:{},accounting:{}};
    const get=path=>path.split('/').filter(Boolean).reduce((v,k)=>v?.[k],state);
    const set=(path,value)=>{const keys=path.split('/').filter(Boolean);if(!keys.length){state=value;return;}let p=state;for(const k of keys.slice(0,-1))p=p[k] ||= {};if(value===null)delete p[keys.at(-1)];else p[keys.at(-1)]=value;};
    const ref=(path='')=>({get:async()=>({val:()=>structuredClone(get(path))}),set:async v=>set(path,v),update:async v=>set(path,{...get(path),...v}),remove:async()=>set(path,null),push:async()=>{},transaction:async fn=>{const next=fn(structuredClone(get(path)));if(next===undefined)return {committed:false};set(path,next);return {committed:true,snapshot:{val:()=>structuredClone(next)}};}});
    const auth={listUsers:async()=>({users:[]}),updateUser:async()=>{},revokeRefreshTokens:async()=>{},deleteUser:async()=>{}};
    class HttpsError extends Error{constructor(code,message){super(message);this.code=code;}}
    const context={exports:{},process:{env:{}},require:name=>name==='./numeric'?require('../functions/numeric'):name==='firebase-admin'?{initializeApp(){},database:()=>({ref}),auth:()=>auth}:name==='firebase-functions/v2/https'?{onCall:fn=>fn,HttpsError}:require(name),Date,console};
    vm.runInNewContext(fs.readFileSync('functions/numeric-services.js','utf8'),context);
    return {api:context.exports,auth,get state(){return state;},request:(uid,data)=>({auth:uid?{uid,token:{auth_time:Math.floor(Date.now()/1000)}}:null,data})};
}
test('anonymous and waiter cannot manage users',async()=>{const f=fixture();for(const uid of [null,'waiter'])await assert.rejects(f.api.manageUsers(f.request(uid,{action:'list'})));});
test('inactive and revoked administrators are rejected',async()=>{const f=fixture();f.state.access.admin.active=false;await assert.rejects(f.api.manageUsers(f.request('admin',{action:'list'})));f.state.access.admin.active=true;f.state.access.admin.revokedAt=Math.floor(Date.now()/1000);await assert.rejects(f.api.manageUsers(f.request('admin',{action:'list'})));});
test('self deletion and removal of another administrator are blocked',async()=>{const f=fixture();await assert.rejects(f.api.manageUsers(f.request('admin',{action:'delete',uid:'admin'})));f.state.access.other={role:'admin',active:true};await assert.rejects(f.api.manageUsers(f.request('admin',{action:'delete',uid:'other'})));});
test('user administration requires recent login',async()=>{const f=fixture(),r=f.request('admin',{action:'list'});r.auth.token.auth_time-=1000;await assert.rejects(f.api.manageUsers(r));});
test('customer price comes from server menu; duplicate request is idempotent',async()=>{const f=fixture(),id=crypto.randomUUID(),r=f.request('customer',{id,table:'1',items:[{id:'coffee',qty:2,price:0}]});const order=await f.api.customerOrder(r);assert.equal(order.total,50);await f.api.customerOrder(r);assert.equal(Object.keys(f.state.orders).length,1);});
test('customer cannot occupy another customer table or send invalid quantities',async()=>{const f=fixture();f.state.tables['1']={status:'occupied',clientId:'other'};await assert.rejects(f.api.customerOrder(f.request('customer',{id:crypto.randomUUID(),table:'1',items:[{id:'coffee',qty:1}]})));await assert.rejects(f.api.customerOrder(f.request('customer',{id:crypto.randomUUID(),table:'2',items:[{id:'coffee',qty:-1}]})));});
test('kitchen cannot deliver and waiter cannot prepare; valid steps preserve prices',async()=>{const f=fixture();f.state.orders.a={status:'قيد التحضير',paymentStatus:'غير مدفوع',total:50};await assert.rejects(f.api.transitionOrder(f.request('waiter',{id:'a',expected:'قيد التحضير',next:'جاهز'})));await f.api.transitionOrder(f.request('kitchen',{id:'a',expected:'قيد التحضير',next:'جاهز',total:0}));assert.equal(f.state.orders.a.total,50);await assert.rejects(f.api.transitionOrder(f.request('kitchen',{id:'a',expected:'جاهز',next:'تم التوصيل'})));await f.api.transitionOrder(f.request('waiter',{id:'a',expected:'جاهز',next:'تم التوصيل'}));assert.equal(f.state.orders.a.status,'تم التوصيل');});
test('only cashier and admin can read aggregate state; access records are excluded',async()=>{const f=fixture();await assert.rejects(f.api.cafeState(f.request('waiter',{action:'read'})));const result=await f.api.cafeState(f.request('cashier',{action:'read'}));assert.equal(result.state.access,undefined);});
test('stale payment cannot overwrite newer orders; injected privileges are ignored',async()=>{const f=fixture(),snapshot=await f.api.cafeState(f.request('cashier',{action:'read'}));f.state.orders.new={total:5};await assert.rejects(f.api.cafeState(f.request('cashier',{action:'commit',...snapshot})));const fresh=await f.api.cafeState(f.request('cashier',{action:'read'}));fresh.state.access={cashier:{role:'admin',active:true}};await f.api.cafeState(f.request('cashier',{action:'commit',...fresh}));assert.equal(f.state.access.cashier.role,'cashier');});
test('rules deny root access and protect permission records; customer reads require ownership query',()=>{const rules=JSON.parse(fs.readFileSync('database.rules.json','utf8')).rules;assert.equal(rules['.read'],false);assert.equal(rules['.write'],false);assert.equal(rules.access.$uid['.write'],undefined);assert.match(rules.orders['.read'],/query.equalTo == auth.uid/);assert.match(rules.accounting['.read'],/accountant/);assert.doesNotMatch(rules.accounting['.read'],/waiter|kitchen/);});
async function authFixture(user,profile){
    let observer,redirect,unlocked=false;
    const instance={setPersistence:async()=>{},onAuthStateChanged:fn=>observer=fn};
    const auth=()=>instance;auth.Auth={Persistence:{SESSION:'session'}};
    const context={Promise,console,location:{pathname:'/admin.html',replace:url=>redirect=url},sessionStorage:{getItem:()=> 'true'},document:{documentElement:{classList:{remove:()=>unlocked=true}},getElementById:()=>null},addEventListener(){},firebase:{apps:[{}],auth,database:()=>({ref:()=>({once:async()=>({val:()=>profile}),on(){}})})}};
    if(user && !user.getIdTokenResult) user.getIdTokenResult=async()=>({claims:{auth_time:100}});
    context.window=context;vm.runInNewContext(fs.readFileSync('js/auth.js','utf8'),context);await context.WardAuth.start();await observer(user);return {redirect,unlocked};
}
test('forged legacy session flags cannot open an admin page',async()=>{const result=await authFixture(null,null);assert.match(result.redirect,/login.html/);assert.equal(result.unlocked,false);});
test('signed-in kitchen account is redirected away from administration',async()=>{const result=await authFixture({uid:'kitchen',isAnonymous:false},{active:true,role:'kitchen'});assert.match(result.redirect,/denied=1/);assert.equal(result.unlocked,false);});
test('verified active administrator unlocks administration',async()=>{const result=await authFixture({uid:'admin',isAnonymous:false,getIdTokenResult:async()=>({claims:{auth_time:100}})},{active:true,role:'admin'});assert.equal(result.redirect,undefined);assert.equal(result.unlocked,true);});
test('numeric identities preserve leading zeroes and normalize Arabic/Persian digits',()=>{const n=require('../functions/numeric');assert.equal(n.digits('٠۰١۲٣۴'),'001234');assert.equal(n.loginEmail('0012'),'0012@staff.ward.invalid');for(const value of ['1234','12345678901a','12345678901','123456789012345678901'])assert.equal(n.validPin(value),false);assert.equal(n.validPin('704829163058'),true);});
test('numeric account creation rejects short or nonnumeric secrets server-side',async()=>{const f=fixture();for(const pin of ['1234','abc123456789','12345678901'])await assert.rejects(f.api.manageUsers(f.request('admin',{action:'create',number:'1001',pin,name:'موظف جديد',role:'waiter'})));});
test('numeric account creation forwards secret only to Auth and never returns or stores it',async()=>{const f=fixture();let captured;f.auth.createUser=async data=>{captured=data;return {uid:'newuser',email:data.email};};const result=await f.api.manageUsers(f.request('admin',{action:'create',number:'٠٠١٢',pin:'٧٠٤٨٢٩١٦٣٠٥٨',name:'موظف جديد',role:'waiter'}));assert.equal(captured.email,'0012@staff.ward.invalid');assert.equal(captured.password,'704829163058');assert.equal(result.number,'0012');assert.equal(JSON.stringify(result).includes('704829163058'),false);assert.equal(JSON.stringify(f.state).includes('704829163058'),false);});
test('only admin may reset another code; successful reset revokes previous sessions',async()=>{const f=fixture();await assert.rejects(f.api.manageUsers(f.request('waiter',{action:'resetPin',uid:'kitchen',pin:'704829163058'})));let updated;f.auth.updateUser=async(uid,data)=>updated={uid,...data};await f.api.manageUsers(f.request('admin',{action:'resetPin',uid:'kitchen',pin:'704829163058'}));assert.equal(updated.password,'704829163058');assert.ok(f.state.access.kitchen.revokedAt);});
test('own numeric code change requires recent authentication and valid digits',async()=>{const f=fixture();await assert.rejects(f.api.changeNumericPin(f.request(null,{pin:'704829163058'})));const request=f.request('waiter',{pin:'704829163058'});request.auth.token.auth_time-=120;await assert.rejects(f.api.changeNumericPin(request));await assert.rejects(f.api.changeNumericPin(f.request('waiter',{pin:'abc'})));await f.api.changeNumericPin(f.request('waiter',{pin:'704829163058'}));assert.ok(f.state.access.waiter.revokedAt);});
